/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoyang_ndkdemo_JNIForNdkbuild */

#ifndef _Included_com_aoyang_ndkdemo_JNIForNdkbuild
#define _Included_com_aoyang_ndkdemo_JNIForNdkbuild
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aoyang_ndkdemo_JNIForNdkbuild
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoyang_ndkdemo_JNIForNdkbuild_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
